const ACTIONS = {
  FETCHING_PRODUCTS_SUCCESS: 'FETCHING_PRODUCTS_SUCCESS',
  FETCHING_PRODUCTS_FAILURE: 'FETCHING_PRODUCTS_FAILURE',
  FETCHING_ORDERS_SUCCESS: 'FETCHING_ORDERS_SUCCESS',
  FETCHING_ORDERS_FAILURE: 'FETCHING_ORDERS_FAILURE',
  SET_CART_PRODUCTS: 'SET_CART_PRODUCTS',
  GET_CART_PRODUCTS: 'GET_CART_PRODUCTS',
  REMOVE_CART_BY_ID_PRODUCTS: 'REMOVE_CART_BY_ID_PRODUCTS',
  SET_LASTEST_PRODUCTS: 'SET_LASTEST_PRODUCTS',
  UNSET_LASTEST_PRODUCTS: 'UNSET_LASTEST_PRODUCTS',
  GET_LASTEST_PRODUCTS: 'GET_LASTEST_PRODUCTS',
};

export default ACTIONS;
