const ACTIONS = {
  FETCHING_PRODUCTS_SUCCESS: 'FETCHING_PRODUCTS_SUCCESS',
  FETCHING_PRODUCTS_FAILURE: 'FETCHING_PRODUCTS_FAILURE',
  FETCHING_ORDERS_SUCCESS: 'FETCHING_ORDERS_SUCCESS',
  FETCHING_ORDERS_FAILURE: 'FETCHING_ORDERS_FAILURE',
};

export default ACTIONS;
