const ACTIONS = {
  FETCHING_PRODUCTS_SUCCESS: 'FETCHING_PRODUCTS_SUCCESS',
  FETCHING_PRODUCTS_FAILURE: 'FETCHING_PRODUCTS_FAILURE',
  FETCHING_ORDERS_SUCCESS: 'FETCHING_ORDERS_SUCCESS',
  FETCHING_ORDERS_FAILURE: 'FETCHING_ORDERS_FAILURE',
  SET_CART_PRODUCTS: 'SET_CART_PRODUCTS',
  GET_CART_PRODUCTS: 'GET_CART_PRODUCTS',
};

export default ACTIONS;
